# Generated by Django 5.0 on 2024-09-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0002_contact_itemlost_email_itemlost_item_found_by_and_more'),
        ('findme', '0003_contact_itemlost_email_itemlost_phone_number_and_more'),
    ]

    operations = [
    ]
