# Generated by Django 5.0 on 2024-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0003_alter_itemlost_item_found_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itemlost',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
